=== KromanXQ/ISTv2/vezba3/autooglas.dtd
<!DOCTYPE AutoOglas[
    <!ELEMENT AutoOglas (Automobil)+>
    <!ELEMENT Automobil (Proizvodjac,Model,Godiste,Farba,ZapreminaMotora,Transmisija,Gorivo,Cena,KontaktProdavca)>
    <!ELEMENT KontaktProdavca (Ime,Prezime,BrojTelefona)>
    <!ELEMENT Proizvodjac (#PCDATA)>
    <!ELEMENT Model (#PCDATA)>
    <!ELEMENT Godiste (#PCDATA)>
    <!ELEMENT Farba (#PCDATA)>
    <!ELEMENT ZapreminaMotora (#PCDATA)>
    <!ELEMENT Transmisija (#PCDATA)>
    <!ELEMENT Gorivo (#PCDATA)>
    <!ELEMENT Cena (#PCDATA)>
    <!ELEMENT Ime (#PCDATA)>
    <!ELEMENT Prezime (#PCDATA)>
    <!ELEMENT BrojTelefona (#PCDATA)>
    <!ATTLIST Model tip (limuzina|hecbek|karavan|kupe|kabriolet|minivan|dzip|pikap) #IMPLIED>
    <!ATTLIST Farba tip (akril|metalik) #REQUIRED>
    <!ATTLIST Transmisija tip (manuelni|auto) #REQUIRED>
    <!ATTLIST Gorivo tng (da|ne) #IMPLIED>
    <!ATTLIST ZapreminaMotora jedinica (ccm|l) #REQUIRED>
    <!ATTLIST Cena valuta (din|eur) #IMPLIED>
]>

=== KromanXQ/ISTv2/vezba3/autooglas.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AutoOglas SYSTEM "autooglas.dtd">
<AutoOglas>
    <Automobil>
        <Proizvodjac>BMW</Proizvodjac>
        <Model tip="limuzina">320i</Model>
        <Godiste>2009</Godiste>
        <Farba tip="metalik">Crna</Farba>
        <ZapreminaMotora jedinica="ccm">1968</ZapreminaMotora>
        <Transmisija tip="auto">6</Transmisija>
        <Gorivo tng="ne">Benzin</Gorivo>
        <Cena valuta="eur">19900</Cena>
        <KontaktProdavca>
            <Ime>Darko</Ime>
            <Prezime>Jovanovic</Prezime>
            <BrojTelefona>+381643345987</BrojTelefona>
        </KontaktProdavca>
    </Automobil>
</AutoOglas>
